### ISSUE TITLE
RSS feed error

### ISSUE THREAD

**Issue by sario528** [fosshostorg/arm-64.com#9]
Blog RSS feed is currently giving the following error:

> Update error 7: At line 302, column 120: mismatched tag

**Comment by amanharwara** [comment]
Should be fixed with the latest commit.

If the post doesn't have a specified `description` or `summary` field in the frontmatter, the code tries to extract the first 1-2 sentences as the summary. But it isn't very sophisticated and hence it grabbed the quote & the image in a post as well.

**Comment by sario528** [comment]
Feed looks good 👍

I'd like to pass along jkoan's suggestion to add a linter check to catch errors per-merge.
